fix: onBackdropPress not working #466
react-native-modal/react-native-modal pull request #485
Opened 2020-10-15 07:18 UTC by yjb94

# Overview

related to #466, #338 
this code will help you onBackdropPress work.

I personally figured out that `TouchablesWithoutFeedback` from 'react-native-gesture-handler' can do the trick.
and also found out that in previous code, `Animated.View` was wrapped inside `TouchablesWithoutFeedback`, which makes it untouchable. (except the status bar. lol)

# Test Plan

I managed to use it for my repository.

2020-10-15 08:32 UTC, yjb94 commented
found out some missing points. will fix and update

2020-10-15 11:47 UTC, yjb94 commented
note things that might be weird

1. Touchable from 'react-native' dosen't work at react-native-modal
- but it works for the only edge part of status bar area for iPhone 

2. Touchable from 'react-native-gesture-handler' disappears when it is absolute.
https://github.com/software-mansion/react-native-gesture-handler/issues/1163
- had to nest `TouchableWithoutFeedback` inside a absolute view.

3. `TouchableWithoutFeedback` is pressed everywhere if the height is 100%
- this is really weird but I don't know why.
- just managed to handle it by subtracting 1 pixel from the caculated height.

2020-10-15 13:09 UTC, rewieer approved these changes
So wrapping the content inside a RNTouchableWithoutFeedback makes the backdrop clickable while the native Touchable doesn't. I had the very same problem a few days ago. Congratulations on finding the root issue !

@mmazzarolo

2020-10-17 08:44 UTC, mmazzarolo requested changes
Hm, I might be missing something here but how would this work without asking everyone to install `react-native-gesture-handler`? Would that be a requirement?

2020-10-19 01:36 UTC, yjb94 commented
@mmazzarolo I thought react-native-gesture-handler was in dependency(because it is used in examples). I've added react-native-gesture-handler in package.json.

2020-10-19 06:44 UTC, mmazzarolo commented
What I mean is: I don't think we should introduce a new dependency (especially a native one) to solve this issue. I'm not 100% sure of what is happening here, but I'm confident this is solvable without adding a new dependency (e.g.: https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/Modal.js this works without any additional dependency)

2020-10-19 09:08 UTC, yjb94 commented
> What I mean is: I don't think we should introduce a new dependency (especially a native one) to solve this issue 🤔 (the example has it because it comes by default with create-react-native-app). Opinions?

@mmazzarolo I totally agree with you with this opinion. but perhaps I've found out this bug was only solvable with r`eact-native-gesture-handler`. And I thought `react-native-gesture-handler` is one of the most used package in react-native ecosystem so It won't bother that much.

> I'm not 100% sure of what is happening here, but I'm confident this is solvable without adding a new dependency (e.g.: https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/Modal.js this works without any additional dependency).

I've just looked up at this repository but found the same bug here too. This bug happens on late iOS X / 11 / 12(never tested but might). I agree with the point you've said but I thought this is a bug from react-native in late iOS. So this was the only way I figured out to solve such an critical issue for my application. :)

2020-10-19 09:50 UTC, mmazzarolo commented
> @mmazzarolo I totally agree with you with this opinion. but perhaps I've found out this bug was only solvable with r`eact-native-gesture-handler`. And I thought `react-native-gesture-handler` is one of the most used package in react-native ecosystem so It won't bother that much.

Makes sense... I'll play with it and let you know, and eventually, we can move it as `peerDependency` instead?

> I've just looked up at this repository but found the same bug here too. This bug happens on late iPhone X / 11 / 12(never tested but might). I agree with the point you've said but I thought this is a bug from react-native in late iOS. So this was the only way I figured out to solve such an critical issue for my application. :)

😮 You mean you can reproduce it or that you see it in the code?
I can't reproduce the bug on iPhone 11/12 🤔 And I recently implemented it [here](https://github.com/mmazzarolo/react-native-dialog/blob/master/src/Modal.js) as well and tested it on both Android and iOS (iPhone 8 and 11). 

Btw thanks for the quick replies 👍

2020-10-19 23:43 UTC, yjb94 commented
> 😮 You mean you can reproduce it or that you see it in the code
> I can't reproduce the bug on iPhone 11/12 🤔 And I recently implemented it [here](https://github.com/mmazzarolo/react-native-dialog/blob/master/src/Modal.js) as well and tested it on both Android and iOS (iPhone 8 and 11).

@mmazzarolo I've reproduced it with my iPhone 11... not sure why this is happening. I'll change it to peer dependency after you play with it. thx!

2020-10-20 01:26 UTC, rewieer commented
I'm glad you took a peek at it too, totally missed the new dependency. I'm using it in all my projects already (it's necessary for react-navigation).

2020-11-06 19:19 UTC, rusakovic commented
Confirm.
Simulator iPhone X and above - not on click is working. Not only `onBackdropPress`
Hope, you could fix it.
A very good modal!
@yjb94 Do you have any updates about making requested changes?

2020-12-21 08:01 UTC, trangcongthanh commented
Touchables from `react-native-gesture-handler` [will not work on Android inside Modal](https://github.com/software-mansion/react-native-gesture-handler/issues/139)

2025-03-08 07:06 UTC, closed without merging