fix: remove deprecated function removeListener
react-native-modal/react-native-modal pull request #594
Opened 2021-08-19 16:21 UTC by antoinewg

# Overview

See this issue: https://github.com/react-native-modal/react-native-modal/issues/588

Following the upgrade to react-native 0.65.0 and the deprecation of `DeviceEventEmitter.removeListener` in favor of `.remove()`.
 
# Test Plan

I have patched-package the same code on our project with success but if you can test on your side as well, that would be nice.

2021-08-19 16:32 UTC, mmazzarolo requested changes
Thank you. 
I see you marked it as a `fix`, but I assume we should also restrict the `peerDependency` version of `react-native` ([here](https://github.com/react-native-modal/react-native-modal/blob/90968f394ab24d8d78b4e2ddb7ff8db4333922d3/package.json#L82)) to `>0.65` and ship it as a `major` change instead, right?

2021-08-20 10:51 UTC, exneval commented
@mmazzarolo agreed, this patch is only needed for RN >= 0.65

2021-08-20 13:47 UTC, antoinewg commented
> Thank you.
> I see you marked it as a `fix`, but I assume we should also restrict the `peerDependency` version of `react-native` ([here](https://github.com/react-native-modal/react-native-modal/blob/90968f394ab24d8d78b4e2ddb7ff8db4333922d3/package.json#L82)) to `>0.65` and ship it as a `major` change instead, right?

Thanks, I've updated the commit.

2021-08-21 11:46 UTC, mmazzarolo requested changes
One

2021-08-21 11:46 UTC, mmazzarolo commented on package.json
> +    "react-native": "^0.65.0"
```suggestion
    "react-native": ">=0.65.0"
```

2021-08-21 11:52 UTC, mmazzarolo commented
🤔 tests are failing and I can't check them now, mind taking a look at them? I guess a `typeof` is missing?

2021-08-23 09:25 UTC, antoinewg commented
> 🤔 tests are failing and I can't check them now, mind taking a look at them? I guess a `typeof` is missing?

I fixed it. Indeed I wasn't using the correct type

2021-08-24 10:12 UTC, merged